[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "soilspecdl"
dynamic = ["version"]
description = "Practical deep learning for soil infrared spectroscopy, built on the fastai framework."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Franck Albinet", email = "franckalbinet@gmail.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    'fastai>=2.8.12',
    'fastcore>=2.2.22',
    'fasttransform>=0.0.2',
    'plum-dispatch>=2.9.0',
    'soilspectfm>=0.1.1',
    'soilspecdata>=0.2.1',
    'pandas',
    'kennard-stone',
]

[project.optional-dependencies]
dev = ["nbdev>=3.3.24", "ipykernel", "build", "twine"]
[project.urls]
Repository = "https://github.com/franckalbinet/soilspecdl"
Documentation = "https://franckalbinet.github.io/soilspecdl/"

[project.entry-points.nbdev]
soilspecdl = "soilspecdl._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "soilspecdl.__version__"}

[tool.setuptools.packages.find]
include = ["soilspecdl"]

[tool.setuptools.package-data]
soilspecdl = ["data/*.csv.gz"]

[tool.nbdev]
custom_sidebar = true
