# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/soilspecdl',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/soilspecdl',
                'lib_path': 'soilspecdl'},
  'syms': {'soilspecdl.core': {'soilspecdl.core.foo': ('core.html#foo', 'soilspecdl/core.py')}}}
