"""Fastai DataLoader for spectroscopy data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dataloader.ipynb.

# %% auto #0
__all__ = ['get_mir_k_1k_smp', 'get_ks_splitter', 'get_splitter', 'SpectralTarget', 'TensorSpectrum', 'show_batch',
           'SpectralBlock', 'RegressionFloatBlock', 'get_spectral_dls']

# %% ../nbs/01_dataloader.ipynb #803b246c
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
#from torch.utils.data import DataLoader, SubsetRandomSampler
#from fastai.data.core import DataLoaders
from fastai.torch_core import TensorBase
from fastai.data.block import DataBlock, TransformBlock
from kennard_stone import train_test_split as ks_split
from fastai.data.block import RegressionBlock
from fastai.torch_core import TitledFloat
from plum import dispatch

import logging
logging.getLogger('kennard_stone').setLevel(logging.WARNING)


# %% ../nbs/01_dataloader.ipynb #793adc74
def get_mir_k_1k_smp():
    "Load MIR Kex (exchangeable potassium) 1000 subsamples from OSSL"    
    url = "https://gist.githubusercontent.com/franckalbinet/613654a8908e5fa6bf131b9b267815f3/raw/0feb62ff4d0a26f2befb657aa87745b756de89b0/mir-k-subset-1000.csv"
    df = pd.read_csv(url)
    y = df.iloc[:, -1].to_numpy()
    X = df.iloc[:,:-1].to_numpy()
    wns = df.columns[:-1].to_numpy().astype(int)
    return X, y, wns

# %% ../nbs/01_dataloader.ipynb #0d7cc7f8
def get_ks_splitter(test_size=0.1, valid_size=0.1):
    def _inner(X, y):
        train_val_X, test_X, train_val_idx, test_idx = ks_split(X, np.arange(len(X)), test_size=test_size)
        _, _, train_idx, valid_idx = ks_split(train_val_X, train_val_idx, test_size=valid_size / (1 - test_size))
        return train_idx, valid_idx, test_idx
    return _inner

# %% ../nbs/01_dataloader.ipynb #6abaf166
def get_splitter(train_pct=0.8, valid_pct=0.1, seed=42):
    def _inner(X, y):
        if not np.isclose(train_pct + valid_pct + (1-train_pct-valid_pct), 1.0):
            raise ValueError("Split proportions must sum to 1")
        n = len(X)
        np.random.seed(seed)
        shuffled_idx = np.random.permutation(n)
        train_size = int(train_pct * n)
        valid_size = int(valid_pct * n)
        train_idx = shuffled_idx[:train_size]
        valid_idx = shuffled_idx[train_size:train_size + valid_size]
        test_idx = shuffled_idx[train_size + valid_size:]
        return train_idx, valid_idx, test_idx
    return _inner

# %% ../nbs/01_dataloader.ipynb #ca00acbb
class SpectralTarget(TitledFloat):
    def show(self, ctx=None, **kwargs):
        if ctx is not None: ctx.set_title(f"Target: {self:.3f}")
        return ctx
        
    def __repr__(self): return f"{float(self):.3f}"

# %% ../nbs/01_dataloader.ipynb #b3b6ba0f
class TensorSpectrum(TensorBase):
    wns = None  # set after loading data: TensorSpectrum.wns = wns

    def show(self, ctx=None, title=None, figsize=None, **kwargs):
        if ctx is None: _, ctx = plt.subplots(figsize=figsize)
        ctx.plot(self.__class__.wns, self.squeeze().cpu(), **kwargs)
        ctx.invert_xaxis()
        ctx.grid(True)
        if title is not None: ctx.set_title(f"Target value: {float(title):.3f}")
        return ctx
    
    def __repr__(self): return f"TensorSpectrum(shape={tuple(self.shape)})"

# %% ../nbs/01_dataloader.ipynb #5517f728
@dispatch
def show_batch(
    x:TensorSpectrum, # Spectra (features)
    y, # Soil property (target)
    samples, 
    ctxs=None, 
    max_n=9, 
    ncols=3, 
    figsize=None, 
    **kwargs
    ):
    n = min(len(samples), max_n)
    ncols = min(ncols, n)
    nrows = (n + ncols - 1) // ncols
    if figsize is None: figsize = (6*ncols, 3*nrows)
    fig, axs = plt.subplots(nrows, ncols, figsize=figsize)
    axs = np.array(axs).flatten()
    for s, ax in zip(samples[:n], axs[:n]):
        s[0].show(ctx=ax, title=s[1], **kwargs)
    for ax in axs[n:]: ax.axis('off')
    plt.tight_layout()

# %% ../nbs/01_dataloader.ipynb #0b74f4d0
def SpectralBlock():
    return TransformBlock(type_tfms=lambda x: TensorSpectrum(torch.tensor(x, dtype=torch.float32).unsqueeze(0)))

# %% ../nbs/01_dataloader.ipynb #7b3c460c
def RegressionFloatBlock():
    return TransformBlock(type_tfms=lambda x: SpectralTarget(x))

# %% ../nbs/01_dataloader.ipynb #4a58cc06
def get_spectral_dls(X, y, wns, splitter=None, bs=32):
    if splitter is None: splitter = get_splitter()
    TensorSpectrum.wns = wns
    train_idx, valid_idx, test_idx = splitter(X, y)
    items = list(range(len(X)))
    def _ds_splitter(o): return list(train_idx), list(valid_idx)
    dblock = DataBlock(
        blocks=(SpectralBlock(), RegressionBlock()),
        splitter=_ds_splitter,
        get_x=lambda i: X[i],
        get_y=lambda i: y[i],
    )
    return dblock.dataloaders(items, bs=bs), test_idx
