"""Build fastai DataLoaders from soil spectra

Docs: https://franckalbinet.github.io/soilspecdl/dataloader.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dataloader.ipynb.

# %% auto #0
__all__ = ['get_ks_splitter', 'get_splitter', 'get_pre_splitter', 'TensorSpectrum', 'show_batch', 'SpectralBlock',
           'get_spectral_dls']

# %% ../nbs/01_dataloader.ipynb #803b246c
import numpy as np, torch
from fastcore.all import *
import matplotlib.pyplot as plt
from fastai.torch_core import TensorBase
from fastai.data.block import DataBlock, TransformBlock, RegressionBlock
from kennard_stone import train_test_split as ks_split
from plum import dispatch

import logging
logging.getLogger('kennard_stone').setLevel(logging.WARNING)


# %% ../nbs/01_dataloader.ipynb #1fc41426
def get_ks_splitter(
    test_size=0.1, # Proportion of data to hold out for testing
    valid_size=0.1, # Proportion of remaining data after test holdout for validation
)->callable: # Function splitting (X,y) into train/valid/test idxs
    "Create a Kennard-Stone splitter returning train, validation and test indices"
    def _inner(X, y):
        train_val_X, test_X, train_val_idx, test_idx = ks_split(X, np.arange(len(X)), test_size=test_size)
        _, _, train_idx, valid_idx = ks_split(train_val_X, train_val_idx, test_size=valid_size / (1 - test_size))
        return train_idx, valid_idx, test_idx
    return _inner

# %% ../nbs/01_dataloader.ipynb #6abaf166
def get_splitter(
    train_pct=0.8, # Proportion of data for training
    valid_pct=0.1, # Proportion of data for validation
    seed=42, # Random seed for reproducibility
)->callable: # Function splitting (X,y) into train/valid/test idxs
    "Create a random splitter returning train, validation and test indices"
    if train_pct + valid_pct > 1: raise ValueError("train_pct + valid_pct must not exceed 1")
    def _inner(X, y):
        n = len(X)
        np.random.seed(seed)
        shuffled_idx = np.random.permutation(n)
        train_size = int(train_pct * n)
        valid_size = int(valid_pct * n)
        train_idx = shuffled_idx[:train_size]
        valid_idx = shuffled_idx[train_size:train_size + valid_size]
        test_idx = shuffled_idx[train_size + valid_size:]
        return train_idx, valid_idx, test_idx
    return _inner

# %% ../nbs/01_dataloader.ipynb #247568b1
def get_pre_splitter(
    n_train, # Number of rows in the existing training set
    valid_pct=0.2, # Proportion of training samples for validation
    seed=42 # Random seed for reproducibility
)->callable: # Function splitting (X,y) into train/valid/test idxs
    "Create a splitter for data whose first `n_train` rows form the training set"
    def _inner(X, y):
        n = len(X)
        train_idx = np.arange(n_train)
        test_idx = np.arange(n_train, n)
        valid_size = int(n_train * valid_pct)
        np.random.seed(seed)
        shuffled = np.random.permutation(train_idx)
        return shuffled[valid_size:], shuffled[:valid_size], test_idx
    return _inner

# %% ../nbs/01_dataloader.ipynb #b3b6ba0f
class TensorSpectrum(TensorBase):
    "Spectra tensor that plots each spectrum against its wavenumbers in `wns`"
    def show(self, ctx=None, title=None, figsize=None, **kwargs):
        if ctx is None: _, ctx = plt.subplots(figsize=figsize)
        wns = getattr(self, 'wns', None)
        ctx.plot(range(self.shape[-1]) if wns is None else wns, self.squeeze().cpu(), **kwargs)
        ctx.invert_xaxis()
        ctx.grid(True)
        if title is not None: ctx.set_title(f"Target value: {float(title):.3f}")
        return ctx
    def __repr__(self): return f"TensorSpectrum(shape={tuple(self.shape)})"

# %% ../nbs/01_dataloader.ipynb #5517f728
@dispatch
def show_batch(
    x:TensorSpectrum, # Spectra (features)
    y, # Soil property (target)
    samples, # Decoded (spectrum, target) pairs
    ctxs=None, # Unused: `show_batch` creates its own axes
    max_n=9, # Maximum number of spectra to plot
    ncols=3, # Number of columns in the grid
    figsize=None, # Figure size, by default 6 by 3 inches per plot
    **kwargs # Passed to `TensorSpectrum.show`
):
    "Plot a batch of spectra in a grid, titled with their targets"
    n = min(len(samples), max_n)
    ncols = min(ncols, n)
    nrows = (n + ncols - 1) // ncols
    if figsize is None: figsize = (6*ncols, 3*nrows)
    _, axs = plt.subplots(nrows, ncols, figsize=figsize)
    axs = np.array(axs).flatten()
    for s, ax in zip(samples[:n], axs[:n]): s[0].show(ctx=ax, title=s[1], **kwargs)
    for ax in axs[n:]: ax.axis('off')
    plt.tight_layout()

# %% ../nbs/01_dataloader.ipynb #0b74f4d0
def SpectralBlock(
    wns, # Wavenumbers, attached to each spectrum as `wns`
):
    "Block turning each spectrum array into a `TensorSpectrum` carrying `wns`"
    def _to_tensor(x:np.ndarray): return TensorSpectrum(torch.tensor(x, dtype=torch.float32).unsqueeze(0), wns=wns)
    return TransformBlock(type_tfms=_to_tensor)

# %% ../nbs/01_dataloader.ipynb #ed806b75
def get_spectral_dls(
    X, # Spectral data matrix
    y, # Target values
    wns, # Wavenumbers
    splitter=None, # Function returning train/valid/test idxs
    bs=32, # Batch size
    batch_tfms=None, # Batch transforms, e.g. [StandardizeSpectrum()]
)->tuple: # (DataLoaders with the grid in `dls.wns`, test set indices)
    "Create DataLoaders for spectra, with train, validation and test sets"
    wns = np.asarray(wns)
    if len(wns) != X.shape[-1]: raise ValueError(f"`wns` has {len(wns)} values but `X` has {X.shape[-1]} columns")
    if splitter is None: splitter = get_splitter()
    train_idx, valid_idx, test_idx = splitter(X, y)
    items = list(range(len(X)))
    def _ds_splitter(o): return list(train_idx), list(valid_idx)
    def _get_x(i:int): return X[i]
    def _get_y(i:int): return y[i]
    dblock = DataBlock(blocks=(SpectralBlock(wns), RegressionBlock()), splitter=_ds_splitter, get_x=_get_x, get_y=_get_y, batch_tfms=batch_tfms)
    dls = dblock.dataloaders(items, bs=bs)
    dls.wns = wns
    return dls, test_idx
