"""Models for the SoilspecDL project"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_models.ipynb.

# %% auto #0
__all__ = ['ConvBlockBaseline', 'ConvBlock', 'FeatureExtractor', 'MirzaiCNN', 'cnt_params']

# %% ../nbs/00_models.ipynb #2bb84e93
from functools import partial
import torch
from torch.nn import (Module, AvgPool1d, LeakyReLU,
                      AdaptiveAvgPool1d, Sequential, 
                      Dropout, Linear)

from fastai.layers import ConvLayer
from typing import Callable

# %% ../nbs/00_models.ipynb #d77ba715
class ConvBlockBaseline(Module):    
    def __init__(self, ni, nf):
        super().__init__()
        self.conv = Sequential(
            torch.nn.Conv1d(ni, nf, kernel_size=3, stride=1, padding=1, bias=False),
            torch.nn.BatchNorm1d(nf),
            torch.nn.LeakyReLU(negative_slope=0.1)
        )
        self.pool = torch.nn.AvgPool1d(3)
    
    def forward(self, x): return self.pool(self.conv(x))

# %% ../nbs/00_models.ipynb #654a2525
class ConvBlock(Module):    
    "Convolutional block with pooling."
    def __init__(self, 
                 ni, # input channels
                 nf, # output channels
                 ks=3, # kernel size
                 stride=1, # stride
                 act_cls=partial(LeakyReLU, negative_slope=0.1)
                 ):
        super().__init__()
        self.conv = ConvLayer(ni, nf, ks=ks, stride=stride, bias=False, 
                              # norm_type='NormType.Instance',
                            #   norm_type='NormType.Batch',
                              act_cls=act_cls,
                              ndim=1)
        self.pool = AvgPool1d(3)
    
    def forward(self, x): return self.pool(self.conv(x))

# %% ../nbs/00_models.ipynb #ead64c03
class FeatureExtractor(Module):
    def __init__(self, 
                 in_channel=1, # input channels
                 out_channel=16, # base number of filters
                 conv_block_cls=ConvBlock,
                 ):
        super().__init__()
        nfs = [out_channel * 2**i for i in range(5)]
        self.layers = Sequential(*[
            conv_block_cls(ni=in_channel if i==0 else nfs[i-1], nf=nfs[i]) 
            for i in range(len(nfs))
        ])
        self.adaptive_pool = AdaptiveAvgPool1d(1)
    
    def forward(self, x): 
        x = self.layers(x)
        return self.adaptive_pool(x)

# %% ../nbs/00_models.ipynb #f49cdcea
class MirzaiCNN(Module):
    """
    1D Convolutional Neural Network for spectral data regression/classification.
    
    Based on the architecture proposed in:
    Albinet, F., Peng, Y., Eguchi, T., Smolders, E., Dercon, G., 2022. Prediction of exchangeable potassium in soil through mid-infrared spectroscopy and deep learning: From prediction to explainability. Artificial Intelligence in Agriculture 6, 230–241. https://doi.org/10.1016/j.aiia.2022.10.001
    """
    def __init__(self, 
                 in_channel: int=1, # input channels
                 out_channel: int=16, # base number of filters
                 conv_block_cls: Callable = ConvBlock,
                 is_classifier: bool=False, # if True, model will output probabilities
                 dropout: float=0.4 # dropout rate
                 ):
        super().__init__()
        self.backbone = FeatureExtractor(in_channel, out_channel, conv_block_cls)
        self.head = Sequential(
            Dropout(dropout), 
            Linear(256, 1))
        self.is_classifier = is_classifier
        
    def forward(self, x):
        x = self.backbone(x)
        x = x.squeeze(-1)
        x = self.head(x)
        x = x.squeeze(-1)
        return torch.sigmoid(x) if self.is_classifier else x

# %% ../nbs/00_models.ipynb #86f4147b
def cnt_params(model):
    for name, param in model.named_parameters():
        print(f"{name}: {param.numel():,} parameters")
    print(f"\nTotal: {sum(p.numel() for p in model.parameters()):,} parameters")
