"""1D convolutional neural networks for soil spectra

Docs: https://franckalbinet.github.io/soilspecdl/models.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_models.ipynb.

# %% auto #0
__all__ = ['ConvBlock', 'FeatureExtractor', 'SpectralCNN', 'MirzaiCNN']

# %% ../nbs/00_models.ipynb #2bb84e93
from functools import partial
import torch
from torch.nn import Module, AvgPool1d, LeakyReLU, AdaptiveAvgPool1d, Sequential, Dropout, Linear

from fastai.layers import ConvLayer, NormType
from typing import Callable

# %% ../nbs/00_models.ipynb #654a2525
class ConvBlock(Module):
    "Convolution, normalization and activation, then average pooling"
    def __init__(
        self,
        ni, # input channels
        nf, # output channels
        ks=3, # kernel size
        stride=1, # stride
        pool_sz=3, # pooling kernel size
        act_cls=partial(LeakyReLU, negative_slope=0.1), # activation
        norm_type=NormType.Batch, # normalization, e.g. `NormType.Instance`
    ):
        super().__init__()
        self.conv = ConvLayer(ni, nf, ks=ks, stride=stride, bias=False, act_cls=act_cls, norm_type=norm_type, ndim=1)
        self.pool = AvgPool1d(pool_sz)
    def forward(self, x): return self.pool(self.conv(x))

# %% ../nbs/00_models.ipynb #ead64c03
class FeatureExtractor(Module):
    "Stack of `ConvBlock`s, one per entry of `nfs`, pooled to one vector per spectrum"
    def __init__(
        self,
        in_channel=1, # input channels
        nfs=(16, 32, 64, 128, 256), # output channels of each conv block
        pool_sz=3, # pooling kernel size of each block
        act_cls=partial(LeakyReLU, negative_slope=0.1), # activation
        norm_type=NormType.Batch, # normalization, e.g. `NormType.Instance`
        conv_block_cls=ConvBlock, # conv block class
    ):
        super().__init__()
        self.nf = nfs[-1]
        nis = (in_channel, *nfs[:-1])
        self.layers = Sequential(*[conv_block_cls(ni, nf, pool_sz=pool_sz, act_cls=act_cls, norm_type=norm_type)
            for ni, nf in zip(nis, nfs)])
        self.adaptive_pool = AdaptiveAvgPool1d(1)

    def forward(self, x): return self.adaptive_pool(self.layers(x)).squeeze(-1)


# %% ../nbs/00_models.ipynb #f49cdcea
class SpectralCNN(Module):
    "1D CNN with a `FeatureExtractor` backbone and a linear head, for regression or binary classification"
    def __init__(
        self,
        in_channel:int=1, # input channels
        nfs=(16, 32, 64, 128, 256), # output channels of each conv block
        pool_sz:int=3, # pooling kernel size of each block
        act_cls=partial(LeakyReLU, negative_slope=0.1), # activation
        norm_type=NormType.Batch, # normalization, e.g. `NormType.Instance`
        conv_block_cls:Callable=ConvBlock, # conv block class
        is_classifier:bool=False, # if True, apply a sigmoid to output probabilities
        dropout:float=0.4 # dropout rate
    ):
        super().__init__()
        self.backbone = FeatureExtractor(in_channel, nfs, pool_sz=pool_sz, act_cls=act_cls,
            norm_type=norm_type, conv_block_cls=conv_block_cls)
        self.head = Sequential(Dropout(dropout), Linear(self.backbone.nf, 1))
        self.is_classifier = is_classifier

    def forward(self, x):
        x = self.head(self.backbone(x)).squeeze(-1)
        return torch.sigmoid(x) if self.is_classifier else x


# %% ../nbs/00_models.ipynb #7b623b47
def MirzaiCNN(
    in_channel:int=1, # input channels
    is_classifier:bool=False, # if True, model will output probabilities
    dropout:float=0.4 # dropout rate
)->SpectralCNN:
    "`SpectralCNN` with the architecture of Albinet et al. (2022)"
    return SpectralCNN(in_channel, nfs=(16, 32, 64, 128, 256), pool_sz=3, act_cls=partial(LeakyReLU, negative_slope=0.1),
        norm_type=NormType.Batch, is_classifier=is_classifier, dropout=dropout)
