"""Batch transforms for spectral DataLoaders

Docs: https://franckalbinet.github.io/soilspecdl/transforms.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_transforms.ipynb.

# %% auto #0
__all__ = ['StandardizeSpectrum']

# %% ../nbs/02_transforms.ipynb #3d3ca8da
import torch
from fastcore.all import *
from fasttransform import Transform
from .dataloader import TensorSpectrum

# %% ../nbs/02_transforms.ipynb #b2d8945f
class StandardizeSpectrum(Transform):
    "Standardize each spectrum to zero mean, unit variance across wavenumbers"
    def __init__(self, eps=1e-6): store_attr()
    def encodes(self, x:TensorSpectrum):
        return (x - x.mean(-1, keepdim=True)) / (x.std(-1, keepdim=True) + self.eps)
